### ISSUE TITLE
Unintuitive title of menu item to report a positive test 

### ISSUE THREAD

**Issue by janpalas** [covid19cz/erouska-android#345] opened 2020-09-18 10:29 UTC
Menu item that opens a screen where a user can report a positive test has an unintuitive label "Send data" ("Odeslat data" in Czech version). 

I would suggest "Report positive test" ("Oznámit pozitivní test")  which is IMHO more straightforward.

**Comment by rpodgorny** [comment] 2020-09-18 11:27
i totally agree. i was also wondering what that is supposed to mean (which brought me here)...

**Comment by stepansonsky** [comment] 2020-09-18 13:22
Good point, agree too, I'll forward it to UX team ;-)

**Comment by jetamo** [comment] 2020-09-19 13:15
I'd say that it's not just the label that's unintuitive. I think that such important feature should be more visible and not hidden in a drop down menu.

**Comment by orangesunny** [comment] 2020-10-08 13:05
How does this look after 20 days?

**Comment by davidvavra** [comment] 2020-10-08 14:07
We are working on a redesign of the main screen. Here is a proposal, do you have some feedback?
![erouska design update](https://user-images.githubusercontent.com/395884/95469752-48fdf980-0980-11eb-9dff-b3cff8e719c8.png)

**Comment by janpalas** [comment] 2020-10-08 19:14
@davidvavra that is much better! Fine by me. (Maybe just tell Minister of Health that is not the best strategy to say "eRouska is nice, but practically useless for us" during an important press conference...)

**Comment by davidvavra** [comment] 2020-10-08 19:20
@janpalas "Hygiena" can't use it for tracing, which is a feature, not a bug. True anonymity. It gives the responsibility to the people, not the government.

**Comment by janpalas** [comment] 2020-10-08 19:25
@davidvavra yes, I know, of course. Still, if you want people to use the app, saying a such thing is IMHO not very helpful for the app...

**Comment by orangesunny** [comment] 2020-10-11 17:13
> We are working on a redesign of the main screen. Here is a proposal, do you have some feedback?
> ![erouska design update](https://user-images.githubusercontent.com/395884/95469752-48fdf980-0980-11eb-9dff-b3cff8e719c8.png)

this looks way better, thank you! (Hope for less stars on iOS screen 😃 🤐  )

@davidvavra Can you also share the new look of the screen describing the issue with the "location services off"? Probably in a new issue.

**Comment by davidvavra** [comment] 2020-10-24 13:10
Related pull request, it contains screenshots: https://github.com/covid19cz/erouska-android/pull/436

**Comment by davidvavra** [comment] 2020-10-29 11:20
Hello everyone, we are preparing a new major version which will contain redesigned dashboard, which fixes this issue. Is anyone interested for alfa testing this? If so, we need to whitelist your account in Google Play. Send me your primary Google account, either here or to email david.vavra@erouska.cz

**Comment by davidvavra** [comment] 2020-11-03 15:23
The main screen redesign is now released into beta. Contact david.vavra@erouska.cz, if you want to test it.

**Closed by davidvavra** 2020-11-03 15:23 UTC
Labels: ux
