### ISSUE TITLE
Disabled bluetooth notification even with enabled Bluetooth

### ISSUE THREAD

**Issue by onovy** [covid19cz/erouska-android#160] opened 2020-04-14 06:25 UTC
After disabling of Bluetooth, notification pops up. But Bluetooth notification from eRouska is still there even if I reactivate Bluetooth. Probably related to #146 

Step to reproduce:
1. enable Bluetooth
2. install and register eRouska
3. check it's running in eRouska dashboard
4. disable Blueooth
5. eRouska notification about disabled Bluetooth pops up
6. reenable Bluetooth
7. eRouska notification is still there
8. restarting phone "fixies" problem

![image](https://user-images.githubusercontent.com/1649603/79192319-c8bf6700-7e28-11ea-9fdf-d5ab413aa09c.png)

**Comment by simekadam** [comment] 2020-04-14 06:58
Reproducible on the same Nokia phones you mentioned in the other issue?

**Comment by onovy** [comment] 2020-04-14 07:00
yes (just checked on Nokia 8.1), all of them are Android One phones.

**Comment by skywall** [comment] 2020-04-14 07:53
I really recommend the usage of RxBlePolidea library to avoid this crazy manufacturer / device related issues. Library provides [observable with BT state](https://github.com/Polidea/RxAndroidBle#observing-client-state) based on more than just system BT related broadcasts. 

I can try to implement this, but I don't own affected device so this would be just blind programming.

**Comment by onovy** [comment] 2020-04-14 08:04
>  avoid this crazy manufacturer / device related issues

Nokia are Android One phones, which are clean AOSP + Google services. So what do you mean by "crazy manufacturer"? It's same clean Android as Pixel phones. There is nothing more "pure Android" than this. :)

**Comment by simekadam** [comment] 2020-04-14 08:05
I have a hunch that this is not caused by BT state issues as the app shows the state and works correctly.  And the issue is in how the notification is updated. 
Here the fg notification gets updated by calling `startForeground` repeatedly. https://github.com/covid19cz/erouska-android/blob/a6d5022a74f4bbb657978205d9d789c40ae7c4ce/app/src/main/kotlin/cz/covid19cz/erouska/ui/notifications/CovidNotificationManager.kt#L126

I have a fix in the works.. @onovy could I send you an APK to quickly verify if it helps?

**Comment by onovy** [comment] 2020-04-14 08:06
> I have a fix in the works.. @onovy could I send you an APK to quickly verify if it helps?

yep

**Comment by simekadam** [comment] 2020-04-14 08:06
Btw I have a Xiaomi Android One device and a Pixel 3 and neither can reproduce the problem 🙂 so far  to clean AOSP 😃

**Comment by simekadam** [comment] 2020-04-14 08:11
@skywall we used rxble in the beginning but it didn't work all that well.

**Comment by simekadam** [comment] 2020-04-14 08:18
[covid19-cz-dev-debug.apk.zip](https://github.com/covid19cz/erouska-android/files/4474007/covid19-cz-dev-debug.apk.zip)

If you unzip this there is the apk. Let me know if you need help with how to install it. 
Btw it's a debug build against dev env, so it will install next to your normal installation..just register again..You can use some random number and postpone verification after 30s 🙂

**Comment by onovy** [comment] 2020-04-14 08:42
nope, this doesn't fix the problem. But i found something interesting. I can reproduce bug (in production and in dev version too) only when I disable "service in background" (i don't want "eRouska is active" notification).
![image](https://user-images.githubusercontent.com/1649603/79204274-93247900-7e3c-11ea-8b46-3af8110da424.png)

**Comment by simekadam** [comment] 2020-04-14 08:51
D'oh now I understand what's going on. 
There a two channels as you can see and each has different priority..one is for the ok state and that is what you have disabled. The other we use for errors so that the phone makes sound or buzz to let the user know that the app can no longer work. When bt gets disabled we post the notification again with the same id but different channel and the same thing happens when bt is enabled again. But as the channel is disabled, the new notification is ignored and the system just swallows it while normally the new notificaiton replaces the old one as it has the same id.

**Comment by simekadam** [comment] 2020-04-14 08:51
i can also reproduce it easily now

**Comment by orangesunny** [comment] 2020-05-17 10:41
Looks like a long-running issue. I needed to toggle Bluetooth on my phone, and since then, I am unable to get rid of the notification "eRouška not active". Bluetooth on, pause the app doesn’t help, killing it works, of course. Please, fix it.

I have Samsung S9+, latest official ROM.

**Comment by davidvavra** [comment] 2020-05-19 11:14
It should be fixed in the next update

**Closed** 2020-05-19 11:14 UTC
