### ISSUE TITLE
Consumes ~4x more battery than Mapy.cz tracking

### ISSUE THREAD

**Issue by tomasfejfar** [covid19cz/erouska-android#148] opened 2020-04-13 09:15 UTC
The app consumes excessive battery. Tracking is enabled in both Mapy.cz and erouska. It's apparent that Mapy.cz (that's using GPS) either does some optimization or there is something wrong with the way how erouska manages it's resources. 

Xiaomi Redmi 4x, Android 7.1.2, MIUI 11.0.2

**Two different scenarios:**
After a trip (~3hrs):
![image](https://user-images.githubusercontent.com/642928/79108009-bd5f3380-7d75-11ea-9c61-0a01f139ffab.png)
After sitting on a table for 2hrs:
![image](https://user-images.githubusercontent.com/642928/79108938-aa4d6300-7d77-11ea-9eba-080882b523e0.png)

**Comment by simekadam** [comment] 2020-04-13 12:30
Is there a way how to show more details on that screen? What happens when you tap on the percentage?
Different phones present this data differently. 
Here it's most likely two things. 

- erouška keeps the device awake, which is necessary for high accuracy and frequent scanning, and likely MIUI just adds all (or significant amount) of used power to our score. 
- mapy.cz use Google location services which is a different process independent from the app. 

For example on my phone erouška hardly ever leaves single digits.  

The fact is that the drain is somewhat higher than we would like it to be and we are actively looking in how to make this better.

**Comment by tomasfejfar** [comment] 2020-04-13 14:10
![image](https://user-images.githubusercontent.com/642928/79126902-20b28b00-7da1-11ea-97ce-be1b60bd814b.png)

Generally it lowered my whole runtime from ~ 48h to something like 31h.

**Comment by davidvavra** [comment] 2020-04-13 14:38
We are aware of issues with battery on certain phones. We are looking on ways how to improve battery consumption based on reports, it's one of our highest priorities.

**Comment by simekadam** [comment] 2020-04-13 19:24
> Generally it lowered my whole runtime from ~ 48h to something like 31h.

![image](https://user-images.githubusercontent.com/483556/79152801-22924380-7dcd-11ea-8516-799a6d0fe1c1.png)

**Comment by tomasfejfar** [comment] 2020-04-13 22:31
I knew I should have said it lowered my runtime by 35% :)

**Comment by waclaw66** [comment] 2020-04-15 08:15
Appka nezachrápe (Mi 9T) ...

![Screenshot_2020-04-15-08-44-29-856_com gsamlabs bbm](https://user-images.githubusercontent.com/15554561/79314068-8f0e5f00-7f01-11ea-8385-730cbfff479b.jpg)

BT mám zapnutý pořád kvůli hodinkám, ale s erouskou je nárůst spotřeby enormní.

**Comment by davidvavra** [comment] 2020-04-15 14:18
This is duplicate of #162, let's keep discussion about battery consumption at one place.

**Closed by davidvavra** 2020-04-15 14:18 UTC
