### ISSUE TITLE
Notification not displayed when Bluetooth is off

### ISSUE THREAD

**Issue by R3gi** [covid19cz/erouska-android#463] opened 2020-10-31 23:31 UTC
User has to enable Bluetooth to see notification detail in the app.

The app triggers notification to the system notification area, but the notification in the app (the red panel) is not displayed while Bluetooth is turned off.
Once the user turns it on, the notification is displayed properly.

v2.1.613
Android 9

![BT disabled.png](https://user-images.githubusercontent.com/2983869/97799286-6d6e8e00-1c2d-11eb-834c-a9c9a95c80f1.png)
![BT enabled.png](https://user-images.githubusercontent.com/2983869/97799289-75c6c900-1c2d-11eb-91e5-68a0f87cb9fa.png)

**Comment by davidvavra** [comment] 2020-11-03 15:26
Hey, can you please retest this on latest beta version? Write me your primary Google account to david.vavra@erouska.cz

**Comment by davidvavra** [comment] 2020-11-04 09:08
The author couldn't reproduce, closing.

**Closed by davidvavra** 2020-11-04 09:08 UTC
