### ISSUE TITLE
Warning not shown in notifications

### ISSUE THREAD

**Issue by pe-pan** [covid19cz/erouska-android#400] opened 2020-10-12 15:10 UTC
Warning not shown in notifications area:
1. How it behaves: To see the warning about a contact with a infectious person, one has to open the app. 
2. Expected behavior: I would expect the app gives me a notification in a notification area (like an SMS/WhatsApp/e-mail client/any other apps are doing)

Please note that I only opened the app by an accident (actually wanted to see the number of performed tests / found infected from the previous day). If I did not open the app, I wouldn't know about the warning at all!

Found on Android OnePlus 6 (Android 10, OxygenOS 10.3.5) with eRouška 2.0 from 2020-09-28

**Comment by davidvavra** [comment] 2020-10-12 15:12
Duplicate of #399

**Closed by davidvavra** 2020-10-12 15:12 UTC
