### ISSUE TITLE
State after battery saver turned off

### ISSUE THREAD

**Issue by redhead** [covid19cz/erouska-android#146] opened 2020-04-12 18:52 UTC
Battery saver notification appears even after battery saver was turned off.

What I did:
1) phone had a low battery and went into battery saver mode
2) notification appeared (also see #145)
3) I put the phone on the charger and left it alone
4) came back when phone was charged, and battery saver has turned automatically off
5) notification stayed

I tried:
1) disabling and enabling erouska again (with the in-app button)
2) enabling and disabling the battery saver again (notification appears again, and stays there even after disabling)

erouska still thinks that the battery saver is on anyway

**Comment by redhead** [comment] 2020-04-12 18:53
![Screenshot_20200412-205240](https://user-images.githubusercontent.com/158482/79077173-b269bc00-7cff-11ea-90ad-7f1842a7e57a.png)

**Comment by redhead** [comment] 2020-04-12 19:00
Also it seems like the app is still running fine in the background. However, it saves the same IDs way more often (per minute) than before:

![Screenshot_20200412-205848](https://user-images.githubusercontent.com/158482/79077274-b2b68700-7d00-11ea-95d6-37b309853e57.png)

**Comment by simekadam** [comment] 2020-04-13 06:09
Thanks for the report. Just to clarify..If you restart the phone and start the app again would turning it off and on again manually update the notification state just fine? 
This is weird..
Mind you if I ask one more question? Were you toggling the app's state before taking the screenshot? 

Also what is your Android version and app version? App version is visible when you go to Napoveda → O aplikaci.

**Comment by redhead** [comment] 2020-04-13 08:31
Version: 1.0.381

Yes, I was toggling the pause/resume of erouska. And toggling the battery saver on/off before taking the picture. But that seems changed nothing.

I "fixed" it by force stopping the app yesterday.

Let me try to restart when I get into the state again. If I get to the state again as I didn't try to reproduce it.

**Comment by skywall** [comment] 2020-04-13 10:28
@redhead Can you please also share the phone model name and manufacturer?

**Comment by onovy** [comment] 2020-04-13 13:37
have exactly same issue on Nokia 6.1, 8.1 and 7.2. Restarting phone "fixies" this problem.

**Comment by simekadam** [comment] 2020-04-13 19:00
@redhead did force closing the app really fix the problem? 
I suppose the dashboard (eRouska tab) looked fine? (at least it looks so from the badge)

**Comment by redhead** [comment] 2020-04-13 20:59
Well force stop made the notification disappear. 

Just happened to get into the state again. Manually turning the battery saver on and off again, the notification appeared but never went away.

Dashboard says that erouska is active.

**Comment by simekadam** [comment] 2020-04-13 21:15
Interesting. Does toggling location services cause the same problem?

**Comment by onovy** [comment] 2020-04-14 10:32
@redhead can you confirm if you disabled "service in background" notification on your phone and thus it's same bug as this? https://github.com/covid19cz/erouska-android/issues/160#issuecomment-613307427

Thanks.

**Comment by redhead** [comment] 2020-04-14 11:59
Aha! Yep, confirmed that I have that notification disabled.

**Comment by davidvavra** [comment] 2020-04-15 14:19
Closing this, it's a duplicate of #160

**Closed by davidvavra** 2020-04-15 14:19 UTC
